/**
 * skylark-videojs - A version of video.js that ported to running on skylarkjs.
 * @author Hudaokeji Co.,Ltd
 * @version v0.9.0
 * @link www.skylarkjs.org
 * @license MIT
 */
define(["./utils/fn","./utils/events","./utils/merge-options","./component"],function(e,s,i,r){"use strict";class t extends r{constructor(r,t){let n=t.ResizeObserver||window.ResizeObserver;null===t.ResizeObserver&&(n=!1),super(r,i({createEl:!n,reportTouchActivity:!1},t)),this.ResizeObserver=t.ResizeObserver||window.ResizeObserver,this.loadListener_=null,this.resizeObserver_=null,this.debouncedHandler_=e.debounce(()=>{this.resizeHandler()},100,!1,this),n?(this.resizeObserver_=new this.ResizeObserver(this.debouncedHandler_),this.resizeObserver_.observe(r.el())):(this.loadListener_=(()=>{if(!this.el_||!this.el_.contentWindow)return;const e=this.debouncedHandler_;let i=this.unloadListener_=function(){s.off(this,"resize",e),s.off(this,"unload",i),i=null};s.on(this.el_.contentWindow,"unload",i),s.on(this.el_.contentWindow,"resize",e)}),this.one("load",this.loadListener_))}createEl(){return super.createEl("iframe",{className:"vjs-resize-manager",tabIndex:-1},{"aria-hidden":"true"})}resizeHandler(){this.player_&&this.player_.trigger&&this.player_.trigger("playerresize")}dispose(){this.debouncedHandler_&&this.debouncedHandler_.cancel(),this.resizeObserver_&&(this.player_.el()&&this.resizeObserver_.unobserve(this.player_.el()),this.resizeObserver_.disconnect()),this.loadListener_&&this.off("load",this.loadListener_),this.el_&&this.el_.contentWindow&&this.unloadListener_&&this.unloadListener_.call(this.el_.contentWindow),this.ResizeObserver=null,this.resizeObserver=null,this.debouncedHandler_=null,this.loadListener_=null,super.dispose()}}return r.registerComponent("ResizeManager",t),t});
//# sourceMappingURL=sourcemaps/resize-manager.js.map
