/**
 * skylark-videojs - A version of video.js that ported to running on skylarkjs.
 * @author Hudaokeji Co.,Ltd
 * @version v0.9.0
 * @link www.skylarkjs.org
 * @license MIT
 */
define(["skylark-langx-globals/document","../component","../utils/obj","../utils/events","../utils/fn","../utils/keycode","./volume-control/volume-control","./mute-toggle"],function(e,s,o,t,l,i){"use strict";class n extends s{constructor(e,s={}){void 0!==s.inline?s.inline=s.inline:s.inline=!0,(void 0===s.volumeControl||o.isPlain(s.volumeControl))&&(s.volumeControl=s.volumeControl||{},s.volumeControl.vertical=!s.inline),super(e,s),this.on(e,["loadstart"],this.volumePanelState_),this.on(this.muteToggle,"keyup",this.handleKeyPress),this.on(this.volumeControl,"keyup",this.handleVolumeControlKeyUp),this.on("keydown",this.handleKeyPress),this.on("mouseover",this.handleMouseOver),this.on("mouseout",this.handleMouseOut),this.on(this.volumeControl,["slideractive"],this.sliderActive_),this.on(this.volumeControl,["sliderinactive"],this.sliderInactive_)}sliderActive_(){this.addClass("vjs-slider-active")}sliderInactive_(){this.removeClass("vjs-slider-active")}volumePanelState_(){this.volumeControl.hasClass("vjs-hidden")&&this.muteToggle.hasClass("vjs-hidden")&&this.addClass("vjs-hidden"),this.volumeControl.hasClass("vjs-hidden")&&!this.muteToggle.hasClass("vjs-hidden")&&this.addClass("vjs-mute-toggle-only")}createEl(){let e="vjs-volume-panel-horizontal";return this.options_.inline||(e="vjs-volume-panel-vertical"),super.createEl("div",{className:`vjs-volume-panel vjs-control ${e}`})}dispose(){this.handleMouseOut(),super.dispose()}handleVolumeControlKeyUp(e){i.isEventKey(e,"Esc")&&this.muteToggle.focus()}handleMouseOver(s){this.addClass("vjs-hover"),t.on(e,"keyup",l.bind(this,this.handleKeyPress))}handleMouseOut(s){this.removeClass("vjs-hover"),t.off(e,"keyup",l.bind(this,this.handleKeyPress))}handleKeyPress(e){i.isEventKey(e,"Esc")&&this.handleMouseOut()}}return n.prototype.options_={children:["muteToggle","volumeControl"]},s.registerComponent("VolumePanel",n),n});
//# sourceMappingURL=../sourcemaps/control-bar/volume-panel.js.map
