/**
 * skylark-videojs - A version of video.js that ported to running on skylarkjs.
 * @author Hudaokeji Co.,Ltd
 * @version v0.9.0
 * @link www.skylarkjs.org
 * @license MIT
 */
define(["../utils/dom","../utils/events","../utils/fn","../utils/obj","../event-target","../utils/log"],function(e,t,n,s,o,i){"use strict";const r=e=>"function"==typeof e.name?e.name():"string"==typeof e.name?e.name:e.name_?e.name_:e.constructor&&e.constructor.name?e.constructor.name:typeof e,f=e=>e instanceof o||!!e.eventBusEl_&&["on","one","off","trigger"].every(t=>"function"==typeof e[t]),a=e=>"string"==typeof e&&/\S/.test(e)||Array.isArray(e)&&!!e.length,l=(e,t,n)=>{if(!e||!e.nodeName&&!f(e))throw new Error(`Invalid target for ${r(t)}#${n}; must be a DOM node or evented object.`)},u=(e,t,n)=>{if(!a(e))throw new Error(`Invalid event type for ${r(t)}#${n}; must be a non-empty string or array.`)},g=(e,t,n)=>{if("function"!=typeof e)throw new Error(`Invalid listener for ${r(t)}#${n}; must be a function.`)},d=(e,t,s)=>{const o=t.length<3||t[0]===e||t[0]===e.eventBusEl_;let i,r,f;return o?(i=e.eventBusEl_,t.length>=3&&t.shift(),[r,f]=t):[i,r,f]=t,l(i,e,s),u(r,e,s),g(f,e,s),{isTargetingSelf:o,target:i,type:r,listener:f=n.bind(e,f)}},c=(e,n,s,o)=>{l(e,e,n),e.nodeName?t[n](e,s,o):e[n](s,o)},h={on(...e){const{isTargetingSelf:t,target:n,type:s,listener:o}=d(this,e,"on");if(c(n,"on",s,o),!t){const e=()=>this.off(n,s,o);e.guid=o.guid;const t=()=>this.off("dispose",e);t.guid=o.guid,c(this,"on","dispose",e),c(n,"on","dispose",t)}},one(...e){const{isTargetingSelf:t,target:n,type:s,listener:o}=d(this,e,"one");if(t)c(n,"one",s,o);else{const e=(...t)=>{this.off(n,s,e),o.apply(null,t)};e.guid=o.guid,c(n,"one",s,e)}},any(...e){const{isTargetingSelf:t,target:n,type:s,listener:o}=d(this,e,"any");if(t)c(n,"any",s,o);else{const e=(...t)=>{this.off(n,s,e),o.apply(null,t)};e.guid=o.guid,c(n,"any",s,e)}},off(e,s,o){if(!e||a(e))t.off(this.eventBusEl_,e,s);else{const i=e,r=s;l(i,this,"off"),u(r,this,"off"),g(o,this,"off"),o=n.bind(this,o),this.off("dispose",o),i.nodeName?(t.off(i,r,o),t.off(i,"dispose",o)):f(i)&&(i.off(r,o),i.off("dispose",o))}},trigger(e,n){l(this.eventBusEl_,this,"trigger");const s=e&&"string"!=typeof e?e.type:e;if(!a(s)){const t=`Invalid event type for ${r(this)}#trigger; `+"must be a non-empty string or object with a type key that has a non-empty value.";if(!e)throw new Error(t);(this.log||i).error(t)}return t.trigger(this.eventBusEl_,e,n)}};function p(t,n={}){const{eventBusKey:o}=n;if(o){if(!t[o].nodeName)throw new Error(`The eventBusKey "${o}" does not refer to an element.`);t.eventBusEl_=t[o]}else t.eventBusEl_=e.createEl("span",{className:"vjs-event-bus"});return s.assign(t,h),t.eventedCallbacks&&t.eventedCallbacks.forEach(e=>{e()}),t.on("dispose",()=>{t.off(),window.setTimeout(()=>{t.eventBusEl_=null},0)}),t}return p.isEvented=f,p.addEventedCallback=((e,t)=>{f(e)?t():(e.eventedCallbacks||(e.eventedCallbacks=[]),e.eventedCallbacks.push(t))}),p});
//# sourceMappingURL=../sourcemaps/mixins/evented.js.map
